"""Create Tables

Revision ID: 6fca1f6b70cc
Revises: 
Create Date: 2024-10-26 17:06:10.634095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fca1f6b70cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directions',
    sa.Column('d_uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('d_uuid')
    )
    op.create_table('projects',
    sa.Column('p_uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('close_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('p_uuid')
    )
    op.create_table('users',
    sa.Column('u_uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('surname', sa.String(length=20), nullable=False),
    sa.Column('patronymic', sa.String(length=20), nullable=False),
    sa.Column('hashed_password', sa.String(length=20), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_developer', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('u_uuid')
    )
    op.create_table('directions_projects',
    sa.Column('d_p_uuid', sa.Uuid(), nullable=False),
    sa.Column('p_uuid', sa.UUID(), nullable=True),
    sa.Column('d_uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['d_uuid'], ['directions.d_uuid'], ),
    sa.ForeignKeyConstraint(['p_uuid'], ['projects.p_uuid'], ),
    sa.PrimaryKeyConstraint('d_p_uuid')
    )
    op.create_table('directions_users',
    sa.Column('d_u_uuid', sa.Uuid(), nullable=False),
    sa.Column('u_uuid', sa.UUID(), nullable=True),
    sa.Column('d_uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['d_uuid'], ['directions.d_uuid'], ),
    sa.ForeignKeyConstraint(['u_uuid'], ['users.u_uuid'], ),
    sa.PrimaryKeyConstraint('d_u_uuid')
    )
    op.create_table('tasks',
    sa.Column('t_uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('close_at', sa.DateTime(), nullable=False),
    sa.Column('p_uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['p_uuid'], ['projects.p_uuid'], ),
    sa.PrimaryKeyConstraint('t_uuid')
    )
    op.create_table('tasks_users',
    sa.Column('t_u_uuid', sa.Uuid(), nullable=False),
    sa.Column('u_uuid', sa.UUID(), nullable=True),
    sa.Column('t_uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['t_uuid'], ['tasks.t_uuid'], ),
    sa.ForeignKeyConstraint(['u_uuid'], ['users.u_uuid'], ),
    sa.PrimaryKeyConstraint('t_u_uuid')
    )
    op.create_table('comments',
    sa.Column('c_uuid', sa.Uuid(), nullable=False),
    sa.Column('text', sa.String(length=150), nullable=False),
    sa.Column('t_u_uuid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['t_u_uuid'], ['tasks_users.t_u_uuid'], ),
    sa.PrimaryKeyConstraint('c_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('tasks_users')
    op.drop_table('tasks')
    op.drop_table('directions_users')
    op.drop_table('directions_projects')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('directions')
    # ### end Alembic commands ###
