"""Change len hashed_pass

Revision ID: ea4331da2164
Revises: 639a779864c9
Create Date: 2024-10-26 22:30:47.654504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4331da2164'
down_revision: Union[str, None] = '639a779864c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 't_u_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('directions_projects', 'p_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('directions_projects', 'd_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('directions_users', 'u_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('directions_users', 'd_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tasks', 'p_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tasks_users', 'u_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tasks_users', 't_uuid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=1024),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('tasks_users', 't_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tasks_users', 'u_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tasks', 'p_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('directions_users', 'd_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('directions_users', 'u_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('directions_projects', 'd_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('directions_projects', 'p_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('comments', 't_u_uuid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
