services:
  backend:
    build:
      context: backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
    depends_on:
      - backend